name: simple_progress_indicators
description: Simple progress indicators package with solid colors and gradients. Can be used to show progress or for simple animation.
version: 0.1.0
homepage: https://github.com/artembark/simple_progress_indicators

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
